In [2]:
import requests
import numpy as np

In [3]:
def locator(city_name):
    base_url = "https://geocoding-api.open-meteo.com/v1/search"
    query_parameters = {
        "name" : city_name,
        "count" : 1

    }
    
    try :
        response = requests.get(base_url,params = query_parameters)
        locationdata= response.json()

        if response.status_code == 200  and "results" in locationdata :
            latitude = locationdata["results"][0]["latitude"]
            longitude = locationdata["results"][0]["longitude"]
            return latitude,longitude
        else:
            print(f"Could not find the {city_name} , please check your spelling")
            return None, None 
    except requests.exceptions.RequestException :
        print("Error!! Could not connect to the network")

def weather_data(latitude, longitude):
    base_url1 = "https://api.open-meteo.com/v1/forecast"
    query_parameters_1 = {
        "latitude": latitude,
        "longitude": longitude,
        "daily": ["temperature_2m_max", "rain_sum", "wind_speed_10m_max"],
        "past_days": 5,
        "forecast_days": 1,
	    "timezone": "auto",

        }  
    try: 
        response1= requests.get(base_url1,params = query_parameters_1) 
        weatherdata= response1.json()

        if response1.status_code == 200:
            max_temperature = weatherdata["daily"]["temperature_2m_max"][:5]
            rain_sum = weatherdata["daily"]["rain_sum"][:5]
            max_windspeed = weatherdata["daily"]["wind_speed_10m_max"][:5]
            return [max_temperature,rain_sum , max_windspeed]
        else:
            print("Enter the data carefully")
    except requests.exceptions.RequestException:
        print("Error!! Could not connect to the newtwork")

if __name__ == "__main__":
    cities = []
    for i in range(3):
        city_name = input(f"Enter the name of your city {i+1} ")
        cities.append(city_name)
    weather_matrix= []
    for city in cities:
        latitude, longitude = locator(city)
        if latitude and longitude:
            data = weather_data(latitude, longitude) 
            weather_matrix.append(data)         
    print(weather_matrix)
        



[[[29.7, 30.0, 27.3, 28.8, 30.0], [0.9, 2.5, 12.7, 6.9, 5.3], [11.9, 14.9, 11.6, 18.0, 20.1]], [[20.0, 24.8, 25.8, 30.9, 27.3], [28.2, 11.3, 0.0, 0.2, 5.5], [4.0, 5.0, 3.5, 11.2, 6.8]], [[27.7, 26.2, 26.4, 25.3, 22.9], [0.0, 0.0, 7.3, 0.0, 0.0], [14.5, 19.2, 8.7, 24.0, 13.0]]]


In [4]:
print(cities)
weather_1 = np.array(weather_matrix)
print(weather_1)

['Mumbai', 'Tokyo', 'New York']
[[[29.7 30.  27.3 28.8 30. ]
  [ 0.9  2.5 12.7  6.9  5.3]
  [11.9 14.9 11.6 18.  20.1]]

 [[20.  24.8 25.8 30.9 27.3]
  [28.2 11.3  0.   0.2  5.5]
  [ 4.   5.   3.5 11.2  6.8]]

 [[27.7 26.2 26.4 25.3 22.9]
  [ 0.   0.   7.3  0.   0. ]
  [14.5 19.2  8.7 24.  13. ]]]


In [5]:
weather_actual = np.transpose(weather_1)
print(weather_actual)

[[[29.7 20.  27.7]
  [ 0.9 28.2  0. ]
  [11.9  4.  14.5]]

 [[30.  24.8 26.2]
  [ 2.5 11.3  0. ]
  [14.9  5.  19.2]]

 [[27.3 25.8 26.4]
  [12.7  0.   7.3]
  [11.6  3.5  8.7]]

 [[28.8 30.9 25.3]
  [ 6.9  0.2  0. ]
  [18.  11.2 24. ]]

 [[30.  27.3 22.9]
  [ 5.3  5.5  0. ]
  [20.1  6.8 13. ]]]


In [6]:
city1_temps = weather_actual[ : , 0 , 0]
print(f"Original temperatures for city 1 is {city1_temps}")

Original temperatures for city 1 is [29.7 30.  27.3 28.8 30. ]


In [10]:
sorted_temp1=  np.sort(city1_temps)
print(f"The max temp in Mumbai for the last five days was {sorted_temp1}")
print(f"The max temperature in the last 5 days was {sorted_temp1.max()}°C and minimum temperature was {sorted_temp1.min()}°C")

The max temp in Mumbai for the last five days was [27.3 28.8 29.7 30.  30. ]
The max temperature in the last 5 days was 30.0°C and minimum temperature was 27.3°C


In [20]:
for i in range(0,3):
    city_all_temps = weather_actual[: , 0 , i]
    print(f"{cities[i] } , the max temperatures are {city_all_temps}")


Mumbai , the max temperatures are [29.7 30.  27.3 28.8 30. ]
Tokyo , the max temperatures are [20.  24.8 25.8 30.9 27.3]
New York , the max temperatures are [27.7 26.2 26.4 25.3 22.9]


In [21]:
for i in range(0,3):
    city_all_temps = weather_actual[: , 0 , i]
    print(f"{cities[i] } , the sorted max temperatures are {np.sort(city_all_temps)}")

Mumbai , the sorted max temperatures are [27.3 28.8 29.7 30.  30. ]
Tokyo , the sorted max temperatures are [20.  24.8 25.8 27.3 30.9]
New York , the sorted max temperatures are [22.9 25.3 26.2 26.4 27.7]
